databases:
  - name: wms_app
    ipAllowList: []
    databaseName: wms_app
    user: wms_app

services:
  - type: web
    name: wms_app
    env: ruby
    buildCommand: "./render-build.sh"
    startCommand: "bundle exec rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: wms_app
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false